openapi: 3.0.3
info:
  title: Library
  description: Library API SErver
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
tags:
  - name: Books
    description: Info on all of books in the library and management operations
  - name: User
    description: User registration, login and info
  - name: Reservations
    description: Book reservations
  - name: Loans
    description: Book loans
  - name: Librarian notes
    description: Notes made by librarians on readers
paths:
  /users/login:
    post:
      tags:
        - User
      summary: Login
      description: Login into an existing account
      operationId: userLogin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'email@mail.com'
                password:
                  type: string
                  example: 'VeryStrongPassword'
      responses:
        200:
          description: New response
          content:
            application/json:
              schema:
                :
        200:
          description: New response
          content:
            application/json:
              schema:
                :
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string

  /users/register/librarian:
    post:
      tags:
        - User
      summary: Register a new librarian
      description: Creates a new librarian account
      security:
        - bearerAuth: []
      responses:
        '200': [ ]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserAuthResponseDTO:
      pr