openapi: 3.0.3
info:
  title: Library
  description: Library
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /users/login:
    post:
      summary: Login
      description: Login into an existing account
      operationId: userLogin
      responses:
        '200': []
  /users/register/librarian:
    post:
      summary: Register a new librarian
      description: Creates a new librarian account
      security:
        - bearerAuth: []
      responses:
        '200': [ ]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT